### ISSUE TITLE
Some improvments

### ISSUE THREAD

**Issue by JamesPatageule** [ljessendk/easybinder#1]
Hi, and thans for this very usefull addon.

Some ideas to improve :
- Automatically manage basic types (Converters and components) like Numbers(Long, Float, etc ...), JSR 310 (LocalDate, etc ...)
- Manage new annotations like @Password, @Percent, @Id, etc ...
- Add possibility to order automatic buildAndBind fields creations and choose form layout to add, for example with @FormField(order = 0, screenZone = "myFormLayoutName")
- Add possibility to use Comboboxes with annotation @ComboBoxField(displayProperty = "nested.property")

I maybe can help to improve ;-D

**Comment by JamesPatageule** [comment]
I tried to update the code. i'm working on the 0.0.4-SNAPSHOT

- updated vaadin to 8.1.4
- added "lombok" to project for code reduction
- changed system to allow types inheritance (ex : Number -> Long, Integer, Float, ...)
- Added new simples ComponentRegistry and ConverterRegistry cases
- added simple example "Person" without any adherence (like hibernate) by using JSR 310 types
- added "SimpleBuildAndBindExample" view

I cannot push ...

**Comment by ljessendk** [comment]
Hi James,Thank you for your feedback and your contribution. This sounds very promissing. Could I ask you to submit a pull request with your changes?Br.LarsDen 15. sep. 2017 17.30 skrev JamesPatageule <notifications@github.com>:I tried to update the code. i'm working on the 0.0.4-SNAPSHOT
updated vaadin to 8.1.4added "lombok" to project for code reductionchanged system to allow types inheritance (ex : Number -> Long, Integer, Float, ...)Added new simples ComponentRegistry and ConverterRegistry casesadded simple example "Person" without any adherence (like hibernate) by using JSR 310 typesadded "SimpleBuildAndBindExample" view
I cannot push ...

**Comment by JamesPatageule** [comment]
Hi,

Sorry, not really experimented with Git & github ...

Tried to push new branch, got message 
"Can't connect to any URI: https://github.com/ljessendk/easybinder.git (https://github.com/ljessendk/easybinder.git: git-receive-pack not permitted)"

**Comment by ljessendk** [comment]
Hi,
You should start by creating a fork of my repository (press the "fork" button) and push your changes to your fork.  Maybe the next  step could then be that you send me a link to your fork and I can do a quick review before you submit a pull request. 
I see that you mention lombok. I'm a big fan of lombok but have deliberately choosen not to use lombok in easybinder as use of lombok may not be compatible with every development environmemt (example Eclipse without installing the lombok plugin). so for this reason I prefer not to have the code or examples depend on lombok.

**Comment by JamesPatageule** [comment]
Yeah, i found it !

For lombok, i understand, for now i'm using it, i will clean and remove dependency for the release.

You can find my code (don't finished) in the 0.0.4-SNAPSHOT forked branch

- i added some missing converters and fields factories
- i started the annotation work, i explain how it works.

Based on the bean analysis, the process detect and create form fields, but using descriptors "BeanField" and "BeanFormField" (later, we will got "BeanTableField" too).
The descriptor keep link with the bean, the field, and the form component (and the layout containing it). It also configure it functionnaly and technicaly.
After, we can implement a "VIEW" oriented system to juste set fields visible, readonly and required, like just a "mask". This masks can follow the object life cycle to just adapt the form.

We just need to create a way to override this system when needed (for specific cases).
We can also Override annotation to pre-configure more comple fields (combo, passwords, etc ...)

I need help to implement it, time is missing and my knowledge of Vaadin 8 too ... I'm just trying to 
migrate !

Can i have your feedback about this ?

**Comment by ljessendk** [comment]
Hi James,
I've had a brief look at your code. Some initial comments:
- It seems that your editor aggressively reformats source files. Unfortunately this makes simple diff'ing using the github "compare" function hard to do.
- The code doesn't compile, seems that there is a missing dependency to guava in the pom.xml
- Some of the unit tests no longer runs:
-- Some unit tests are now broken due to the introduction of FormField. It seems that the FormField annotation is now requred in order for fields to be build and bound. I would prefer that by default all fields are build and bound. Maybe an annotation could instead be added when a field is not supposed to be build and bound.
-- Some unit tests are now broken due to change of converter null handling. For non-primitive types I think that "" should be mapped to null.
- I like the addition of JSR310 converters and component builders.

Can you take a look at the above, points, especially the source code formatting part? When done I can take a second look.

**Comment by JamesPatageule** [comment]
Thanks for the answer.

Sorry for the formatter and the dependency.
I didn't correct the unit tests because it's just a preliminary version introducing the idea and the goal.

It seems to be too far from your vision, you prefer a rigid model against a configurable model. In my mind both are possible (for example class annotation @AutoBind)

I wanna contribute with ideas, i understand that it's your project and in fact, seems to be hard.
I don't need code review in your project, i wanna explain and try to give ideas for growing this plugin.

I wanna open a discuss with fonctionnalities. Don't worry, i can do this ideas outside your project.

**Comment by ljessendk** [comment]
Closing this issue for now.
A few of the ideas presented in this issue has been implemented (example the JSR310 converters and component builders).
