### ISSUE TITLE
BinderStatusChangeEvent not fired for conversion errors

### ISSUE THREAD

**Issue by NBau** [ljessendk/easybinder#2]
If I e.g. put a non-digit character into a number field, the error marker is shown, but the BinderStatusChangeEvent is not fired.

**Comment by ljessendk** [comment]
Yes, you're right, the event was only fired for JSR303 validation errors not for conversion errors. This has been corrected now. Also BinderStatusChangeEvent has been extended with a methods such that it is possible to check if there is conversion errors, validation errors or any error (conversion or validation)

**Comment by NBau** [comment]
Thank you for this quick reply.
