### ISSUE TITLE
Group validation issue?

### ISSUE THREAD

**Issue by ReinhardClaus** [ljessendk/easybinder#3]
Added a property

```
@Size(min=3, max=10)
String test;

public String getTest() {
 [.....]
```

to the Flight class. Using the BuildAndBindExample, when I have a Sbt set, Gate is marked red. When I set test to "A" (size violation) the red marking on gate disappears. I'm investigating, will follow up in case I find something out.

**Comment by ReinhardClaus** [comment]
Hmm validateConstraintsForDefaultGroup(..) in ValidatorImpl.java (Hibernate) exits when the first group fails to validate, so no chance to access the validation errors of other groups. I'll keep looking maybe there's a way around that.

**Comment by ReinhardClaus** [comment]
Didn't find a way to do that but found a workaround (Using the Flight example: Added "FlightValidGate" and "FlightValidTest" Class Level Validators along with payloads that specify the "offending" properties. In AutoBinder's handleConstraintViolations I could then pass the error onto the vaadin fields using the code attached)
```
[....]
	// Bean level validation error
	if (statusLabel != null) {
		statusLabel.setValue(f.apply(v));
	}
			
	v.getConstraintDescriptor().getPayload().forEach(aClass -> {
		handleError(validationErrorMap.get(aClass.getSimpleName()), f.apply(v));
	});
[....]
```

Anyway just a workaround so leaving this open for now maybe there's a less hacky solution ;)

**Comment by ljessendk** [comment]
Looks like this is the standard behavior of GroupSequenceProvider/GroupSequence according to this answer on StackOverflow where they also suggest to use class level validators instead: https://stackoverflow.com/questions/27173960/jsr303-apply-all-validation-groups-defined-in-sequence.

I also found this post where they implement a class level validator and perform some operations on ConstraintValidatorContext, maybe something like this could work?

**Comment by ReinhardClaus** [comment]
That looks promising, thanks. (Btw wouldn't mind closing this issue as it's not an actual issue at least not one with easybinder)
